# Generated by Django 4.2a1 on 2023-03-27 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_rename_date_register_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusPay',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='ordername',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='master',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='master',
            name='surname',
        ),
        migrations.AddField(
            model_name='register',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hello.client'),
        ),
        migrations.AddField(
            model_name='register',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hello.master'),
        ),
    ]
