# Generated by Django 4.2a1 on 2023-03-27 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_statuspay'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='statuspay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hello.statuspay'),
        ),
    ]
