# Generated by Django 4.2a1 on 2023-03-27 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_remove_register_statuspay_alter_register_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='mpay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='m_pay', to='hello.statuspay'),
        ),
        migrations.AddField(
            model_name='register',
            name='statuspay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s_pay', to='hello.statuspay'),
        ),
    ]
