# Generated by Django 4.2a1 on 2023-03-27 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_alter_register_client_alter_register_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='hello.client'),
        ),
        migrations.AlterField(
            model_name='register',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='master', to='hello.master'),
        ),
    ]
