# Generated by Django 4.2a1 on 2023-03-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_alter_client_name_alter_master_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя мастера'),
        ),
    ]
