# Generated by Django 4.2a1 on 2023-03-29 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_alter_master_email_alter_master_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rest',
            field=models.IntegerField(default=0, verbose_name='Остаток депозита'),
        ),
        migrations.AlterField(
            model_name='register',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='hello.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='register',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='register',
            name='invoice',
            field=models.IntegerField(default=0, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='register',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='master', to='hello.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='register',
            name='mpay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='m_pay', to='hello.statuspay', verbose_name='Оплата мастеру'),
        ),
        migrations.AlterField(
            model_name='register',
            name='mprice',
            field=models.FloatField(default=0, verbose_name='Цена для мастера'),
        ),
        migrations.AlterField(
            model_name='register',
            name='ordername',
            field=models.CharField(max_length=100, verbose_name='Название заказа'),
        ),
        migrations.AlterField(
            model_name='register',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена заказа'),
        ),
        migrations.AlterField(
            model_name='register',
            name='ready',
            field=models.BooleanField(default=False, verbose_name='Готовность'),
        ),
        migrations.AlterField(
            model_name='register',
            name='statuspay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s_pay', to='hello.statuspay', verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='statuspay',
            name='status',
            field=models.CharField(max_length=30, verbose_name='Тип статуса'),
        ),
    ]
