# Generated by Django 4.2a1 on 2023-04-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_alter_client_discount_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspay',
            name='sign',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='statuspay',
            name='status',
            field=models.CharField(max_length=30, verbose_name='Статус'),
        ),
    ]
